name: Terraform Deploy

on:
  push:
    branches:
      - main
      - dev
      - staging

env:
  TF_VERSION: '1.12.2'
  AWS_REGION: 'us-east-1'
  SECURE_ARTIFACTS_BUCKET: ${{ secrets.SECURE_ARTIFACTS_BUCKET }}

jobs:
  terraform:
    name: 'Terraform Workflow'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Terraform environment variables
        run: |
          echo "TF_VAR_project_url=https://github.com/${{ github.repository }}" >> $GITHUB_ENV
          echo "TF_VAR_access_ip=${{ secrets.ACCESS_IP }}" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ./env
        run: terraform init -input=false

      - name: Terraform Format Check
        working-directory: ./env
        run: terraform fmt -check

      - name: Terraform Validate
        working-directory: ./env
        run: terraform validate

      - name: Terraform Plan
        working-directory: ./env
        run: terraform plan -input=false

#- name: Terraform Apply
      #  working-directory: ./env
      #  run: terraform apply -auto-approve

#- name: Upload SSH Private Key to Secure Artifacts S3 Bucket
      #  run: |
      #    KEY_NAME=$(terraform output -raw name)
      #    aws s3 cp ./modules/ssh_key/${KEY_NAME}-key-pair.pem s3://${SECURE_ARTIFACTS_BUCKET}/ssh-keys/${KEY_NAME}-key-pair.pem
